export type Lang = "id" | "en";

export const socials = {
  x: "https://x.com/gmgndi",
  handle: "@gmgndi",
};

export const copy = {
  id: {
    nav: {
      about: "Tentang",
      work: "Kerja",
      projects: "Proyek",
      gallery: "Galeri",
      contact: "Kontak",
    },
    hero: {
      kicker: "On-chain sejak 2017",
      title: "Sembilan tahun di jaringan.",
      lead: "gmgndi menjaga infrastruktur, meneliti protokol, mengalokasikan di ICO/IDO, mengejar retroactive, menyediakan likuiditas, dan merawat komunitas — tanpa perlu menjadi yang paling ramai di ruangan.",
      pfpCaption: "PFP · identitas on-chain",
    },
    stats: [
      { value: "9 th", label: "di industri kripto" },
      { value: "Node", label: "validator operator" },
      { value: "ICO/IDO", label: "early allocation" },
      { value: "Retro", label: "airdrop & farming" },
    ],
    about: {
      kicker: "Tentang",
      title: "Bukan turis siklus.",
      paragraphs: [
        "Saya masuk ke kripto ketika industri ini masih terdengar seperti desas-desus. Grafiknya kasar, komunitasnya kecil, dan yang bertahan bukan yang paling keras bersuara — melainkan yang paling sabar belajar.",
        "Sembilan tahun kemudian, saya masih di sini. Nama saya gmgndi. Kerja saya ada di lapisan yang jarang ramai: menjaga validator node, meneliti protokol sebelum menjadi narasi, berinvestasi di ICO/IDO, mengejar peluang retroactive, menyediakan likuiditas di Uniswap dan Meteora, dan merawat orang-orang yang tetap datang setelah hype mereda.",
        "Infrastruktur adalah bentuk perhatian. Alokasi awal adalah bentuk keyakinan yang terukur. Retroactive adalah bentuk kesabaran terhadap jalur yang belum diberi label. Likuiditas adalah bentuk kepercayaan. Komunitas adalah yang tersisa ketika grafik menjadi senyap.",
      ],
    },
    work: {
      kicker: "Kerja",
      title: "Lima lapisan yang saya jaga.",
      items: [
        {
          id: "validator",
          index: "01",
          title: "Validator node",
          image: "/images/gmgndi-validator.png",
          imageAlt: "Menara node validator di kabut, dengan benang cahaya emas",
          body: "Saya mengoperasikan validator sebagai janji, bukan sebagai hiasan. Uptime adalah cara paling sunyi untuk berkata: jaringannya boleh diandalkan. Di balik setiap epoch yang berjalan, ada mesin yang harus tetap hidup — termasuk ketika pasar sedang tidur.",
        },
        {
          id: "research",
          index: "02",
          title: "Web3 research",
          image: "/images/gmgndi-research.png",
          imageAlt: "Meja riset malam dengan peta protokol yang menyala",
          body: "Sebelum alokasi, ada pembacaan. Saya meneliti mekanisme, insentif, dan titik gagal sebuah protokol — bukan judulnya. Riset yang baik tidak selalu menghasilkan tweet. Ia menghasilkan keputusan yang lebih tenang, dan lebih sulit untuk diubah-ubah oleh siklus.",
        },
        {
          id: "early-allocation",
          index: "03",
          title: "ICO / IDO & retroactive",
          image: "/images/gmgndi-research.png",
          imageAlt: "Meja riset malam untuk alokasi ICO IDO dan jalur retro",
          body: "Saya berinvestasi di ICO dan IDO dengan disiplin riset: tokenomics, distribusi, unlock, dan risiko eksekusi tim. Di sisi lain, saya mengerjakan jalur retroactive — berinteraksi dengan protokol sebelum reward diberi nama, lalu menunggu keputusan yang tidak bisa dipaksa. Early allocation adalah taruhan terukur; retro adalah kesabaran yang terstruktur.",
        },
        {
          id: "liquidity",
          index: "04",
          title: "Liquidity provider",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Dua sungai likuiditas emas dan sian bertemu di kolam gelap",
          body: "Di Uniswap dan Meteora saya duduk di dalam pasar, bukan di luarnya. Menyediakan likuiditas berarti ikut menanggung spread, volatilitas, dan kedalaman. Itu kerja yang tidak spektakuler — dan justru karena itu, ia penting.",
        },
        {
          id: "community",
          index: "05",
          title: "Komunitas Web3",
          image: "/images/gmgndi-community.png",
          imageAlt: "Lingkaran siluet di sekitar cahaya kecil di lanskap gelap",
          body: "Jaringan bukan hanya node dan kolam. Ia adalah ruang, percakapan, dan orang yang terus muncul. Saya membangun komunitas agar Web3 tidak hanya menjadi spekulasi, tetapi juga tempat orang belajar, bertahan, dan membangun bersama.",
        },
      ],
    },
    projects: {
      kicker: "Proyek",
      title: "Beberapa kerja yang hidup on-chain.",
      lead: "Dari bot Telegram untuk komunitas degen sampai agen LP otonom di Solana — proyek yang lahir dari kebutuhan nyata di lapangan.",
      items: [
        {
          id: "scanme",
          year: "2025",
          title: "Scanme",
          subtitle: "Agen LP otonom · Meteora DLMM",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Visual likuiditas emas dan sian untuk Scanme",
          body: "Agen manajemen likuiditas Meteora DLMM di Solana yang digerakkan LLM. Menyaring pool, membuka dan menutup posisi, mengklaim fee, lalu belajar dari performa — lewat loop Hunter dan Healer yang berjalan terjadwal.",
          tags: ["Solana", "Meteora", "DLMM", "LLM", "Telegram"],
        },
        {
          id: "meteora-scanner",
          year: "2025",
          title: "Meteora Pool Scanner",
          subtitle: "Telegram bot · Jupiter & DLMM",
          image: "/images/gmgndi-research.png",
          imageAlt: "Visual riset protokol untuk scanner Meteora",
          body: "Bot Telegram yang memindai token Jupiter dan pool Meteora DLMM, lalu mengirim sinyal ke komunitas. Dibangun agar riset pool tidak mengandalkan scroll manual di dashboard.",
          tags: ["Solana", "Meteora", "Jupiter", "Telegram"],
        },
        {
          id: "uniswap-robinhood",
          year: "2025",
          title: "Uniswap Robinhood Bot",
          subtitle: "Telegram bot · Uniswap Data API",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Visual likuiditas untuk bot Uniswap",
          body: "Bot grup Telegram: tempel contract address di jaringan Robinhood, dapat daftar pool Uniswap lengkap dengan TVL, volume, fee, dan APR. Dirancang untuk topik forum degen agar info pool muncul tepat di tempatnya.",
          tags: ["Ethereum L2", "Uniswap", "Telegram", "DeFi"],
        },
        {
          id: "validator-ops",
          year: "2017–",
          title: "Validator Operations",
          subtitle: "Infrastruktur node · uptime",
          image: "/images/gmgndi-validator.png",
          imageAlt: "Menara validator untuk operasi node",
          body: "Operasi validator sebagai praktik jangka panjang: menjaga mesin tetap hidup, memantau epoch, dan memperlakukan uptime sebagai komitmen terhadap jaringan — bukan sekadar status di Discord.",
          tags: ["Validator", "Infra", "Node"],
        },
        {
          id: "lp-desk",
          year: "Ongoing",
          title: "Liquidity Desk",
          subtitle: "Uniswap · Meteora",
          image: "/images/gmgndi-community.png",
          imageAlt: "Visual komunitas dan likuiditas",
          body: "Praktik LP langsung di Uniswap dan Meteora: mengatur kedalaman, membaca range, dan menanggung volatilitas. Pengalaman ini yang kemudian menjadi fondasi bot dan agen otomatis.",
          tags: ["LP", "Uniswap", "Meteora", "Market making"],
        },
        {
          id: "early-retro",
          year: "Ongoing",
          title: "ICO / IDO & Retroactive",
          subtitle: "Early allocation · airdrop paths",
          image: "/images/gmgndi-research.png",
          imageAlt: "Visual riset untuk ICO IDO dan retroactive",
          body: "Desk alokasi awal: mengevaluasi ICO/IDO (tokenomics, unlock, risiko tim) dan menjalankan jalur retroactive di protokol sebelum reward diumumkan. Bukan spekulasi buta — melainkan riset, sizing, dan kesabaran.",
          tags: ["ICO", "IDO", "Retroactive", "Airdrop", "Research"],
        },
      ],
    },
    gallery: {
      kicker: "Galeri",
      title: "Beberapa bingkai dari dunia yang saya huni.",
      items: [
        {
          src: "/images/gmgndi-pfp.png",
          alt: "PFP NFT gmgndi",
          caption: "PFP",
        },
        {
          src: "/images/gmgndi-validator.png",
          alt: "Karya visual validator node",
          caption: "Validator",
        },
        {
          src: "/images/gmgndi-liquidity.png",
          alt: "Karya visual likuiditas on-chain",
          caption: "Liquidity",
        },
        {
          src: "/images/gmgndi-research.png",
          alt: "Karya visual riset protokol",
          caption: "Research",
        },
        {
          src: "/images/gmgndi-community.png",
          alt: "Karya visual komunitas Web3",
          caption: "Community",
        },
      ],
    },
    contact: {
      kicker: "Kontak",
      title: "Temukan saya di jaringan.",
      body: "Jika Anda membangun, meriset, atau menjaga likuiditas — percakapan yang tenang selalu terbuka.",
      cta: "Tulis di X",
    },
    footer: "gmgndi · on-chain since 2017",
  },
  en: {
    nav: {
      about: "About",
      work: "Work",
      projects: "Projects",
      gallery: "Gallery",
      contact: "Contact",
    },
    hero: {
      kicker: "On-chain since 2017",
      title: "Nine years in the network.",
      lead: "gmgndi keeps infrastructure alive, studies protocols, allocates into ICO/IDO rounds, pursues retroactive paths, provides liquidity, and tends community — without needing to be the loudest person in the room.",
      pfpCaption: "PFP · on-chain identity",
    },
    stats: [
      { value: "9 yrs", label: "in crypto" },
      { value: "Node", label: "validator operator" },
      { value: "ICO/IDO", label: "early allocation" },
      { value: "Retro", label: "airdrop & farming" },
    ],
    about: {
      kicker: "About",
      title: "Not a tourist of cycles.",
      paragraphs: [
        "I entered crypto when the industry still felt like a rumor. The charts were crude, the rooms were small, and the people who lasted were not the loudest — they were the most patient students.",
        "Nine years later, I am still here. My name is gmgndi. My work lives in the quieter layers: running validator nodes, researching protocols before they become narratives, investing in ICO/IDO rounds, pursuing retroactive opportunities, providing liquidity on Uniswap and Meteora, and keeping company with people who remain after the hype thins out.",
        "Infrastructure is a form of care. Early allocation is measured conviction. Retroactive work is patience along unlabeled paths. Liquidity is a form of trust. Community is what remains when the candles go quiet.",
      ],
    },
    work: {
      kicker: "Work",
      title: "Five layers I keep.",
      items: [
        {
          id: "validator",
          index: "01",
          title: "Validator node",
          image: "/images/gmgndi-validator.png",
          imageAlt: "A validator tower in fog, gold threads of light radiating out",
          body: "I operate validators as a promise, not a badge. Uptime is the quietest way to say the network can be trusted. Behind every epoch that lands, a machine has to stay awake — especially when the market is asleep.",
        },
        {
          id: "research",
          index: "02",
          title: "Web3 research",
          image: "/images/gmgndi-research.png",
          imageAlt: "A night research desk with faint holographic protocol maps",
          body: "Before allocation, there is reading. I study mechanisms, incentives, and failure points — not headlines. Good research does not always produce a thread. It produces calmer decisions, harder to reverse when the cycle turns.",
        },
        {
          id: "early-allocation",
          index: "03",
          title: "ICO / IDO & retroactive",
          image: "/images/gmgndi-research.png",
          imageAlt: "A night research desk for ICO IDO allocation and retro paths",
          body: "I invest in ICO and IDO rounds with research discipline: tokenomics, distribution, unlocks, and team execution risk. Separately, I work retroactive paths — interacting with protocols before rewards are named, then waiting for decisions that cannot be forced. Early allocation is sized conviction; retro is structured patience.",
        },
        {
          id: "liquidity",
          index: "04",
          title: "Liquidity provider",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Two molten rivers of gold and cyan meeting in a dark pool",
          body: "On Uniswap and Meteora I sit inside the market, not outside it. Providing liquidity means carrying spread, volatility, and depth. It is unspectacular work — which is exactly why it matters.",
        },
        {
          id: "community",
          index: "05",
          title: "Web3 community",
          image: "/images/gmgndi-community.png",
          imageAlt: "Silhouettes gathered around a small light in a dark landscape",
          body: "A network is not only nodes and pools. It is rooms, conversations, and people who keep showing up. I build community so Web3 is not only speculation, but a place to learn, stay, and make things together.",
        },
      ],
    },
    projects: {
      kicker: "Projects",
      title: "Work that lives on-chain.",
      lead: "From Telegram bots for degen rooms to an autonomous LP agent on Solana — projects born from real field needs.",
      items: [
        {
          id: "scanme",
          year: "2025",
          title: "Scanme",
          subtitle: "Autonomous LP agent · Meteora DLMM",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Gold and cyan liquidity visual for Scanme",
          body: "An LLM-powered Meteora DLMM liquidity agent on Solana. It screens pools, opens and closes positions, claims fees, and learns from performance — through scheduled Hunter and Healer loops.",
          tags: ["Solana", "Meteora", "DLMM", "LLM", "Telegram"],
        },
        {
          id: "meteora-scanner",
          year: "2025",
          title: "Meteora Pool Scanner",
          subtitle: "Telegram bot · Jupiter & DLMM",
          image: "/images/gmgndi-research.png",
          imageAlt: "Protocol research visual for the Meteora scanner",
          body: "A Telegram bot that scans Jupiter tokens and Meteora DLMM pools, then pushes signals to the community — so pool research does not depend on endless dashboard scrolling.",
          tags: ["Solana", "Meteora", "Jupiter", "Telegram"],
        },
        {
          id: "uniswap-robinhood",
          year: "2025",
          title: "Uniswap Robinhood Bot",
          subtitle: "Telegram bot · Uniswap Data API",
          image: "/images/gmgndi-liquidity.png",
          imageAlt: "Liquidity visual for the Uniswap bot",
          body: "A Telegram group bot: paste a contract address on the Robinhood network and get Uniswap pools with TVL, volume, fees, and APR. Built for a degen forum topic so pool intel lands where people already are.",
          tags: ["Ethereum L2", "Uniswap", "Telegram", "DeFi"],
        },
        {
          id: "validator-ops",
          year: "2017–",
          title: "Validator Operations",
          subtitle: "Node infrastructure · uptime",
          image: "/images/gmgndi-validator.png",
          imageAlt: "Validator tower for node operations",
          body: "Validator operations as long-term practice: keeping machines alive, watching epochs, and treating uptime as a commitment to the network — not just a Discord role.",
          tags: ["Validator", "Infra", "Node"],
        },
        {
          id: "lp-desk",
          year: "Ongoing",
          title: "Liquidity Desk",
          subtitle: "Uniswap · Meteora",
          image: "/images/gmgndi-community.png",
          imageAlt: "Community and liquidity visual",
          body: "Hands-on LP practice on Uniswap and Meteora: shaping depth, reading ranges, and carrying volatility. That desk experience became the foundation for the bots and autonomous agents.",
          tags: ["LP", "Uniswap", "Meteora", "Market making"],
        },
        {
          id: "early-retro",
          year: "Ongoing",
          title: "ICO / IDO & Retroactive",
          subtitle: "Early allocation · airdrop paths",
          image: "/images/gmgndi-research.png",
          imageAlt: "Research visual for ICO IDO and retroactive work",
          body: "An early-allocation desk: evaluating ICO/IDO rounds (tokenomics, unlocks, team risk) and running retroactive paths on protocols before rewards are announced. Not blind speculation — research, sizing, and patience.",
          tags: ["ICO", "IDO", "Retroactive", "Airdrop", "Research"],
        },
      ],
    },
    gallery: {
      kicker: "Gallery",
      title: "A few frames from the world I inhabit.",
      items: [
        {
          src: "/images/gmgndi-pfp.png",
          alt: "gmgndi NFT profile picture",
          caption: "PFP",
        },
        {
          src: "/images/gmgndi-validator.png",
          alt: "Validator node artwork",
          caption: "Validator",
        },
        {
          src: "/images/gmgndi-liquidity.png",
          alt: "On-chain liquidity artwork",
          caption: "Liquidity",
        },
        {
          src: "/images/gmgndi-research.png",
          alt: "Protocol research artwork",
          caption: "Research",
        },
        {
          src: "/images/gmgndi-community.png",
          alt: "Web3 community artwork",
          caption: "Community",
        },
      ],
    },
    contact: {
      kicker: "Contact",
      title: "Find me on the network.",
      body: "If you are building, researching, or keeping liquidity — a quiet conversation is always open.",
      cta: "Write on X",
    },
    footer: "gmgndi · on-chain since 2017",
  },
} as const;
